export const restaurantOptionsList = [
    "American",
    "Breakfast",
    "Burgers",
    "Pizzas",
    "Sandwiches",
    "Sushi",
    "Cafe",
    "Deserts",
    "BBQ",
    "Mexican",
    "Chinese",
    "Japanese",
    "French",
    "Greek",
    "Bulgarian",
    "Indian",
    "Italian",
    "Spanish",
    "Salads",
    "Ice cream"
];